# Site
title: NewBrand
email: info@davidgurr.com
description: We represent a community of professionals and students that are dedicated to pursuing excellence and integrity in design. Sign up below for more information on upcoming events.
mission: We represent a community of professionals and students that are dedicated to pursuing excellence and integrity in design. Sign up below for more information on upcoming events.
baseurl: "/designforum"
url: "https://zacharyrnewton.github.io"
enforce_ssl: designforum.us

# Social accounts
instagram_username: DesignForumUS
twitter_username: DesignForumUS
facebook_username: DesignForumUS

instagram_url: https://www.instagram.com/designforumus/
twitter_url: https://twitter.com/designforumus/
facebook_url: https://www.facebook.com/Designforumus/
slack_invite_link: https://join.slack.com/t/designforumus/shared_invite/enQtMzQxNDU0MTA5MjgwLWU2ZDIzNzY4NzM1ZTA1YTM2M2I0NDUxNTM3OTljZWUxZTQ1ODE2ZDE2OWVhNTk4ZTE0Zjc3NDJhZGQ1MTJiNzY


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
sass:
  sass_dir: _sass
  style: compressed
